package com.example.letscheck.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight             = Color(0xFF7D96B9)
val onPrimaryLight           = Color(0xFFFFFFFF)
val primaryContainerLight    = Color(0xFF1C4B86)
val onPrimaryContainerLight  = Color(0xFFDCE7FF)
val secondaryLight           = Color(0xFF515F78)
val onSecondaryLight         = Color(0xFFFFFFFF)
val secondaryContainerLight  = Color(0xFFD8E4FF)
val onSecondaryContainerLight = Color(0xFF3B4962)
val tertiaryLight            = Color(0xFF173882)
val onTertiaryLight          = Color(0xFFFFFFFF)
val tertiaryContainerLight   = Color(0xFF405CA8)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight               = Color(0xFFBA1A1A)
val onErrorLight             = Color(0xFFFFFFFF)
val errorContainerLight      = Color(0xFFFFDAD6)
val onErrorContainerLight    = Color(0xFF410002)
val backgroundLight          = Color(0xFFF9F9FF)
val onBackgroundLight        = Color(0xFF1A1C20)
val surfaceLight             = Color(0xFFF9F9FF)
val onSurfaceLight           = Color(0xFF1A1C20)
val surfaceVariantLight      = Color(0xFFDFE2EE)
val onSurfaceVariantLight    = Color(0xFF434750)
val outlineLight             = Color(0xFF737781)
val outlineVariantLight      = Color(0xFFC3C6D1)
val scrimLight               = Color(0xFF000000)
val inverseSurfaceLight      = Color(0xFF2F3035)
val inverseOnSurfaceLight    = Color(0xFFF0F0F6)
val inversePrimaryLight      = Color(0xFFA8C8FF)
val surfaceDimLight          = Color(0xFFD9D9DF)
val surfaceBrightLight       = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3F9)
val surfaceContainerLight    = Color(0xFFEEEDF3)
val surfaceContainerHighLight = Color(0xFFE8E8ED)
val surfaceContainerHighestLight = Color(0xFFE2E2E8)
val checkedGreen             = Color(0xFF199619)
val checkedDeepGreen         = Color(0xFF085F0A)


val primaryDark              = Color(0xFF323C4B)
val onPrimaryDark            = Color(0xFFFFFFFF)
val primaryContainerDark     = Color(0xFF003265)
val onPrimaryContainerDark   = Color(0xFF9FC2FF)
val secondaryDark            = Color(0xFFB8C7E4)
val onSecondaryDark          = Color(0xFF233148)
val secondaryContainerDark   = Color(0xFF313F57)
val onSecondaryContainerDark = Color(0xFFC5D4F2)
val tertiaryDark             = Color(0xFFB3C5FF)
val onTertiaryDark           = Color(0xFF012A76)
val tertiaryContainerDark    = Color(0xFF23428C)
val onTertiaryContainerDark  = Color(0xFFD6DEFF)
val errorDark                = Color(0xFFFFB4AB)
val onErrorDark              = Color(0xFF690005)
val errorContainerDark       = Color(0xFF93000A)
val onErrorContainerDark     = Color(0xFFFFDAD6)
val backgroundDark           = Color(0xFF111317)
val onBackgroundDark         = Color(0xFFE2E2E8)
val surfaceDark              = Color(0xFF111317)
val onSurfaceDark            = Color(0xFFE2E2E8)
val surfaceVariantDark       = Color(0xFF434750)
val onSurfaceVariantDark     = Color(0xFFC3C6D1)
val outlineDark              = Color(0xFF8D919B)
val outlineVariantDark       = Color(0xFF434750)
val scrimDark                = Color(0xFF000000)
val inverseSurfaceDark       = Color(0xFFE2E2E8)
val inverseOnSurfaceDark     = Color(0xFF2F3035)
val inversePrimaryDark       = Color(0xFF345F9B)
val surfaceDimDark           = Color(0xFF111317)
val surfaceBrightDark        = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E12)
val surfaceContainerLowDark  = Color(0xFF1A1C20)
val surfaceContainerDark     = Color(0xFF1E2024)
val surfaceContainerHighDark = Color(0xFF282A2E)
val surfaceContainerHighestDark = Color(0xFF333539)
val checkedLowDark           = Color(0xFF19AF19)






